<a href="https://colab.research.google.com/github/jiruneko/DeepLearning-_PyTorch/blob/main/PyTorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

u = np.array([-1, 1, 2])

exp_u = np.exp(u)
exp_u

array([0.36787944, 2.71828183, 7.3890561 ])

In [8]:
exp_u.sum()

10.475217368561138

In [9]:
a = exp_u / exp_u.sum()
a

array([0.03511903, 0.25949646, 0.70538451])

In [10]:
a.sum()

1.0

In [11]:
import torch

In [12]:
torch.__version__

'2.1.0+cu121'

In [13]:
import torch.nn as nn
fc = nn.Linear(3, 2)
fc.weight

Parameter containing:
tensor([[-0.1337,  0.3818, -0.2857],
        [ 0.0458,  0.0295, -0.1999]], requires_grad=True)

In [14]:
fc.bias

Parameter containing:
tensor([-0.4007, -0.5208], requires_grad=True)

In [15]:
torch.manual_seed(1)

In [16]:
fc = nn.Linear(3, 2)

fc.weight

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)

In [17]:
fc.bias

Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)

In [18]:
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
x

tensor([[1., 2., 3.]])

In [19]:
x.type

<function Tensor.type>

In [20]:
u = fc(x)
u

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward0>)

In [21]:
import torch.nn.functional as F

#ReLU関数
h = F.relu(u)
h

tensor([[0.0000, 0.5164]], grad_fn=<ReluBackward0>)

In [22]:
# 乱数のシードを固定
torch.manual_seed(1)

# 入力値の定義
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
x

tensor([[1., 2., 3.]])

In [23]:
fc1 = nn.Linear(3, 2)
fc2 = nn.Linear(2, 1)

u1 = fc1(x)
u1

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward0>)

In [24]:
h1 = F.relu(u1)

y = fc2(h1)
y

tensor([[0.1514]], grad_fn=<AddmmBackward0>)

In [25]:
t = torch.tensor([[1]], dtype=torch.float32)
t

tensor([[1.]])

In [26]:
loss = F.mse_loss(t, y)
loss

tensor(0.7201, grad_fn=<MseLossBackward0>)

In [27]:
from sklearn.datasets import load_iris

# Irisデータセットの読み込み
x, t = load_iris(return_X_y=True)

# サイズの確認
x.shape, t.shape

((150, 4), (150,))

In [28]:
# 型の確認
type(x), type(t)

(numpy.ndarray, numpy.ndarray)

In [29]:
# データ型の確認
x.dtype, t.dtype

(dtype('float64'), dtype('int64'))

In [30]:
x = torch.tensor(x, dtype=torch.float32)
t = torch.tensor(t, dtype=torch.int64)

type(x), type(t)

(torch.Tensor, torch.Tensor)

In [31]:
x.dtype, t.dtype

(torch.float32, torch.int64)

In [32]:
from torch.utils.data import TensorDataset

# 入力値と目標値をまとめて、１つのオブジェクトdatasetに変換
dataset = TensorDataset(x, t)
dataset

In [33]:
type(dataset)

torch.utils.data.dataset.TensorDataset

In [34]:
dataset[0]

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))

In [35]:
type(dataset[0])

tuple

In [36]:
# １サンプル目の入力値
dataset[0][0]

tensor([5.1000, 3.5000, 1.4000, 0.2000])

In [37]:
# １サンプル目の目標値
dataset[0][1]

tensor(0)

In [38]:
# サンプル数はlenで取得可能
len(dataset)

150

In [39]:
# 各データセットのサンプル数を決定
# train : val: test = 60% : 20% : 20%
n_train = int(len(dataset) * 0.6)
n_val = int(len(dataset) * 0.2)
n_test = len(dataset) - n_train - n_val

# それぞれのサンプル数を確認
n_train, n_val, n_test

(90, 30, 30)

In [40]:
from torch.utils.data import random_split

#  ランダムに分割を行うため、シードを固定して再現性を確保
torch.manual_seed(0)

#  データセットの分割
train, val, test = random_split(dataset, [n_train, n_val, n_test])

#　サンプル数の確認
len(train), len(val), len(test)

(90, 30, 30)

In [41]:
batch_size = 10

from torch.utils.data import DataLoader

#  shuffleはデフォルトでFalseのため、学習データのみTrueに指定
train_loader = DataLoader(train, batch_size, shuffle=True)
val_loader = DataLoader(val, batch_size)
test_loader = DataLoader(test, batch_size)

In [42]:
class Net(nn.Module):

  # 使用するオブジェクトを定義
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(4, 4)
    self.fc2 = nn.Linear(4, 3)

  # 準電波
  def forward(self, x):
    x = self.fc1(x)
    x = F.relu(x)
    x = self.fc2(x)
    return x

In [43]:
# 乱数のシードを固定して再現性を確保
torch.manual_seed(0)

# インスタンス化
net = Net()

# ネットワークの確認
net

Net(
  (fc1): Linear(in_features=4, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
)

In [44]:
criterion = nn.CrossEntropyLoss()
criterion

CrossEntropyLoss()

In [45]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [46]:
# バッチサイズ分のサンプルの抽出
batch = next(iter(train_loader))
batch

[tensor([[5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [6.5000, 3.0000, 5.5000, 1.8000],
         [6.9000, 3.1000, 5.4000, 2.1000],
         [6.3000, 2.5000, 4.9000, 1.5000],
         [7.1000, 3.0000, 5.9000, 2.1000],
         [5.8000, 2.7000, 4.1000, 1.0000],
         [7.0000, 3.2000, 4.7000, 1.4000],
         [6.7000, 3.0000, 5.0000, 1.7000],
         [7.2000, 3.6000, 6.1000, 2.5000]]),
 tensor([0, 0, 2, 2, 1, 2, 1, 1, 1, 2])]

In [47]:
x, t  = batch
x

tensor([[5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [7.2000, 3.6000, 6.1000, 2.5000]])

In [48]:
t

tensor([0, 0, 2, 2, 1, 2, 1, 1, 1, 2])

In [49]:
# 全結合層fc1の重み
net.fc1.weight

Parameter containing:
tensor([[-0.0037,  0.2682, -0.4115, -0.3680],
        [-0.1926,  0.1341, -0.0099,  0.3964],
        [-0.0444,  0.1323, -0.1511, -0.0983],
        [-0.4777, -0.3311, -0.2061,  0.0185]], requires_grad=True)

In [50]:
# 全結合層fc1のバイアス
net.fc1.bias

Parameter containing:
tensor([ 0.1977,  0.3000, -0.3390, -0.2177], requires_grad=True)

In [51]:
# 全結合層fc2の重み
net.fc2.weight

Parameter containing:
tensor([[ 0.1816,  0.4152, -0.1029,  0.3742],
        [-0.0806,  0.0529,  0.4527, -0.4638],
        [-0.3148, -0.1266, -0.1949,  0.4320]], requires_grad=True)

In [52]:
y = net.forward(x)
y

tensor([[-0.2557, -0.2605, -0.4679],
        [-0.2041, -0.2834, -0.5574],
        [-0.2786, -0.2244, -0.3632],
        [-0.2552, -0.2214, -0.3703],
        [-0.3241, -0.2302, -0.3493],
        [-0.2788, -0.2244, -0.3631],
        [-0.3241, -0.2302, -0.3493],
        [-0.3241, -0.2302, -0.3493],
        [-0.3090, -0.2282, -0.3539],
        [-0.1884, -0.2129, -0.3907]], grad_fn=<AddmmBackward0>)

In [53]:
y = net(x)
y

tensor([[-0.2557, -0.2605, -0.4679],
        [-0.2041, -0.2834, -0.5574],
        [-0.2786, -0.2244, -0.3632],
        [-0.2552, -0.2214, -0.3703],
        [-0.3241, -0.2302, -0.3493],
        [-0.2788, -0.2244, -0.3631],
        [-0.3241, -0.2302, -0.3493],
        [-0.3241, -0.2302, -0.3493],
        [-0.3090, -0.2282, -0.3539],
        [-0.1884, -0.2129, -0.3907]], grad_fn=<AddmmBackward0>)

In [54]:
loss = criterion(y, t)
loss

tensor(1.0882, grad_fn=<NllLossBackward0>)

In [55]:
net.fc1.weight.grad

net.fc1.bias.grad

net.fc2.weight.grad

net.fc2.bias.grad

In [56]:
loss.backward()

In [57]:
net.fc1.weight.grad

tensor([[-0.2311, -0.1731, -0.0627, -0.0139],
        [ 0.7327,  0.3358,  0.6025,  0.2229],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [58]:
net.fc1.bias.grad

tensor([-0.0461,  0.1060,  0.0000,  0.0000])

In [59]:
net.fc2.weight.grad

tensor([[-0.0652,  0.0259,  0.0000,  0.0000],
        [ 0.0366,  0.0227,  0.0000,  0.0000],
        [ 0.0285, -0.0486,  0.0000,  0.0000]])

In [60]:
net.fc2.bias.grad

tensor([ 0.1415, -0.0452, -0.0963])

In [61]:
optimizer.step()

In [62]:
net.fc1.weight

Parameter containing:
tensor([[ 0.0194,  0.2855, -0.4053, -0.3666],
        [-0.2659,  0.1005, -0.0702,  0.3742],
        [-0.0444,  0.1323, -0.1511, -0.0983],
        [-0.4777, -0.3311, -0.2061,  0.0185]], requires_grad=True)

In [63]:
net.fc1.bias

Parameter containing:
tensor([ 0.2023,  0.2894, -0.3390, -0.2177], requires_grad=True)

In [64]:
net.fc2.weight

Parameter containing:
tensor([[ 0.1881,  0.4126, -0.1029,  0.3742],
        [-0.0843,  0.0506,  0.4527, -0.4638],
        [-0.3176, -0.1217, -0.1949,  0.4320]], requires_grad=True)

In [65]:
net.fc2.bias

Parameter containing:
tensor([-0.3382, -0.2256, -0.3397], requires_grad=True)

In [66]:
torch.cuda.is_available()

False

In [67]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [68]:
net.to(device)

Net(
  (fc1): Linear(in_features=4, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
)

In [69]:
x = x.to(device)
x

tensor([[5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [7.2000, 3.6000, 6.1000, 2.5000]])

In [70]:
t = t.to(device)
t

tensor([0, 0, 2, 2, 1, 2, 1, 1, 1, 2])

In [71]:
optimizer.zero_grad()

In [72]:
net.fc1.weight.grad

In [73]:
net.fc1.bias.grad

In [74]:
max_epoch = 1

torch.manual_seed(0)

net = Net().to(device)

optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

for epoch in range(max_epoch):

  for batch in train_loader:

    x, t = batch

    x = x.to(device)
    t = t.to(device)

    optimizer.zero_grad()

    y = net(x)

    loss = criterion(y, t)

    print('loss:', loss.item())

    loss.backward()

    optimizer.step()

loss: 1.0881630182266235
loss: 1.0393922328948975
loss: 1.0028115510940552
loss: 1.0250868797302246
loss: 1.0088638067245483
loss: 0.9351975321769714
loss: 0.8939588665962219
loss: 0.9765418171882629
loss: 0.9651517868041992


In [75]:
y_label = torch.argmax(y, dim=1)

y_label

tensor([0, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [76]:
t

tensor([1, 1, 0, 2, 1, 2, 0, 2, 1, 1])

In [77]:
y_label == t

tensor([False,  True,  True, False,  True, False,  True, False, False, False])

In [78]:
(y_label == t).sum

<function Tensor.sum>

In [79]:
(y_label == t).sum() * 1.0

tensor(4.)

In [81]:
acc = (y_label == t).sum() * 1.0 /len(t)
acc

tensor(0.4000)

In [82]:
torch.manual_seed(0)

net = Net().to(device)

optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

In [83]:
for epoch in range(max_epoch):

    for batch in train_loader:

        x, t = batch

        x = x.to(device)
        t = t.to(device)

        optimizer.zero_grad()

        y = net(x)

        loss = criterion(y, t)

        # New：正解率の算出
        y_label = torch.argmax(y, dim=1)
        acc  = (y_label == t).sum() * 1.0 / len(t)
        print('accuracy:', acc)

        loss.backward()

        optimizer.step()

accuracy: tensor(0.6000)
accuracy: tensor(0.8000)
accuracy: tensor(0.6000)
accuracy: tensor(0.6000)
accuracy: tensor(0.6000)
accuracy: tensor(0.5000)
accuracy: tensor(0.4000)
accuracy: tensor(0.2000)
accuracy: tensor(0.4000)


In [84]:
# 正解率の計算
def calc_acc(data_loader):

    with torch.no_grad():

        accs = []  # 各バッチごとの結果格納用

        for batch in data_loader:
            x, t = batch
            x = x.to(device)
            t = t.to(device)
            y = net(x)

            y_label = torch.argmax(y, dim=1)
            acc  = (y_label == t).sum() * 1.0 / len(t)
            accs.append(acc)

    # 全体の平均を算出
    avg_acc = torch.tensor(accs).mean()

    return avg_acc

In [85]:
# 検証データで確認
val_acc = calc_acc(val_loader)
val_acc

tensor(0.6333)

In [86]:
# テストデータで確認
test_acc = calc_acc(test_loader)
test_acc

tensor(0.5667)